#!/bin/bash

### BEGIN INIT INFO
# Provides:          dataLogger
# Required-Start:    $all
# Required-Stop:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to add the capability to shutdown the Raspberry Pi with a button
# Description:       Script to add the capability to shutdown the Raspberry Pi with a button
### END INIT INFO

case "$1" in
    start)
        cd /root
	/usr/bin/python ./dataLogger.py &
	echo $! > /tmp/.dataLogger-pid
        ;;
    stop)
	kill `cat /tmp/.dataLogger-pid`
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;

    *)
        echo "Usage: $0 start|stop|restart|reload"
        exit 1
esac

exit 0
